-- +goose Up
CREATE TABLE product_policies (id text PRIMARY KEY, tenant_id text NOT NULL, code text NOT NULL, version integer NOT NULL CHECK(version > 0), currency char(3) NOT NULL, minimum_amount bigint NOT NULL CHECK(minimum_amount > 0), maximum_amount bigint NOT NULL CHECK(maximum_amount >= minimum_amount), minimum_term_days integer NOT NULL CHECK(minimum_term_days > 0), maximum_term_days integer NOT NULL CHECK(maximum_term_days >= minimum_term_days), active boolean NOT NULL DEFAULT true, UNIQUE(tenant_id, code, version));
CREATE TABLE pricing_policies (id text PRIMARY KEY, tenant_id text NOT NULL, product_policy_id text NOT NULL REFERENCES product_policies(id), version integer NOT NULL CHECK(version > 0), annual_rate_bps integer NOT NULL CHECK(annual_rate_bps >= 0), origination_fee_bps integer NOT NULL CHECK(origination_fee_bps >= 0), active boolean NOT NULL DEFAULT true, UNIQUE(tenant_id, product_policy_id, version));
CREATE TABLE credit_applications (id text PRIMARY KEY, tenant_id text NOT NULL, product_policy_id text NOT NULL REFERENCES product_policies(id), relationship_id text NOT NULL, amount bigint NOT NULL CHECK(amount > 0), currency char(3) NOT NULL, term_days integer NOT NULL CHECK(term_days > 0), purpose text NOT NULL, product_policy_version integer NOT NULL, status text NOT NULL CHECK(status IN ('pending_review','offered','accepted','declined','cancelled')), submitted_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX credit_applications_review_queue_idx ON credit_applications(tenant_id, status, submitted_at);
CREATE TABLE credit_offers (application_id text PRIMARY KEY REFERENCES credit_applications(id), quote_id text NOT NULL UNIQUE, product_policy_version integer NOT NULL CHECK(product_policy_version > 0), pricing_policy_version integer NOT NULL CHECK(pricing_policy_version > 0), principal bigint NOT NULL CHECK(principal > 0), interest bigint NOT NULL CHECK(interest >= 0), fees bigint NOT NULL CHECK(fees >= 0), total bigint NOT NULL CHECK(total = principal + interest + fees), term_days integer NOT NULL CHECK(term_days > 0), expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE credit_decision_audit (id bigserial PRIMARY KEY, application_id text NOT NULL REFERENCES credit_applications(id), actor text NOT NULL, action text NOT NULL, reason text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE OR REPLACE FUNCTION prohibit_credit_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'credit decision audit is immutable'; END; $$;
CREATE TRIGGER credit_decision_audit_immutable BEFORE UPDATE OR DELETE ON credit_decision_audit FOR EACH ROW EXECUTE FUNCTION prohibit_credit_audit_mutation();
-- +goose Down
DROP TABLE credit_decision_audit, credit_offers, credit_applications, pricing_policies, product_policies; DROP FUNCTION prohibit_credit_audit_mutation();
